# Generated by Django 5.0.4 on 2024-04-23 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('color', models.CharField(max_length=255)),
                ('paint_number', models.CharField(max_length=12)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='media')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='media')),
                ('hex', models.CharField(blank=True, max_length=7, null=True)),
                ('rgb', models.CharField(blank=True, max_length=12, null=True)),
                ('cmyk', models.CharField(blank=True, max_length=12, null=True)),
                ('paint_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paints', to='epaintapi.painttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
